name: Publish

on:
  release:
    types: [published]

jobs:
  upload_asset:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
      - uses: burrunan/gradle-cache-action@v1
        with:
          gradle-distribution-sha-256-sum-warning: false
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          cache: gradle
          java-version: 17
      - run: chmod +x gradlew
      - name: Build And Publish To Maven
        run: ./gradlew build --no-daemon
      - name: Update GitHub Release
        uses: tubone24/update_release@v1.3.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          body_path: CHANGELOG.md
          is_append_body: true
      - uses: Kir-Antipov/mc-publish@v3.2
        with:
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

          modrinth-featured: false

          changelog-file: CHANGELOG.md
